apiVersion: batch/v1
kind: Job
metadata:
  name: modflow-job-template
spec:
  template:
    spec:
      volumes:
      - name: nfs-vol
        persistentVolumeClaim:
          claimName: <nfs-volume-name>
      containers:
      - name: modflow
        image: <modflow-job-image>
        args: ["hflow-job-execute", "<task_id>", "<redis_url>"]
        # args: ["sleep", "infinity"]
        volumeMounts:
        - mountPath: /workspace
          name: nfs-vol
          subPath: boi/modflow/cekcyn17
      restartPolicy: Never
  backoffLimit: 1