apiVersion: batch/v1
kind: Job
metadata:
  name: modflow-job-template
spec:
  template:
    spec:
      volumes:
      - name: nfs-vol
        persistentVolumeClaim:
         claimName: <nfs-pvc-name>
      containers:
      - name: modflow
        image: watermodelling/modflow-job:latest
        imagePullPolicy: "Always"
       args: ["hflow-job-execute", "<task_id>", "<redis_url>"]
        volumeMounts:
        - mountPath: /workspace
          name: nfs-vol
      restartPolicy: Never
  backoffLimit: 1